"""
Tests for: Hotel search with invalid check-in date
Generated by llm_to_test.py using Ollama.
"""

import pytest
from pages.hotels_page import HotelsPage


# Priority: High
def test_checkin_date_before_minimum_allowed_date_eg_20230101(page):
    """TC-1: Check-in date before minimum allowed date (e.g., 2023-01-01)"""
    hotels = HotelsPage(page)
    hotels.open()

    hotels.checkin_input.fill("2023-01-01")
    hotels.search_button.click()
    page.wait_for_load_state("networkidle")
    error = page.locator(".error, .alert, [class*='error']").first
    assert error.text_content().strip() == "Check-in date must be on or after 2023-01-02"
    assert not hotels.has_results()


# Priority: High
def test_checkin_date_after_maximum_allowed_date_eg_20231231(page):
    """TC-2: Check-in date after maximum allowed date (e.g., 2023-12-31)"""
    hotels = HotelsPage(page)
    hotels.open()

    hotels.checkin_input.fill("2023-12-31")
    hotels.search_button.click()
    page.wait_for_load_state("networkidle")
    error = page.locator(".error, .alert, [class*='error']").first
    assert error.text == "Check-in date must be on or before 2023-12-30"
    assert not hotels.has_results()


# Priority: Medium
def test_invalid_date_format_eg_20230231(page):
    """TC-3: Invalid date format (e.g., `2023/02/31`)"""
    hotels = HotelsPage(page)
    hotels.open()

    hotels.checkin_input.fill("2023/02/31")
    hotels.search_button.click()
    hotels.page.wait_for_load_state("networkidle")
    error = hotels.page.locator(".error, .alert, [class*='error']").first
    assert error.text == "Invalid date format. Please use YYYY-MM-DD format" and not hotels.has_results()


# Priority: Medium
def test_nonexistent_date_in_current_year_eg_february_31_in_a_nonleap(page):
    """TC-4: Non-existent date in current year (e.g., February 31 in a non-leap year)"""
    hotels = HotelsPage(page)
    hotels.open()

    hotels.checkin_input.fill("2023-02-31")
    hotels.search_button.click()
    page.wait_for_load_state("networkidle")
    error = page.locator(".error, .alert, [class*='error']").first
    assert error.text_content() == "February has 28 days. Please enter a valid date"
    assert not hotels.has_results()


# Priority: Medium
def test_empty_checkin_date_field(page):
    """TC-5: Empty check-in date field"""
    hotels = HotelsPage(page)
    hotels.open()

    hotels.search_button.click()
    hotels.page.wait_for_load_state("networkidle")
    error = hotels.page.locator(".error, .alert, [class*='error']").first
    assert error.text_content() == "Check-in date is required"
    assert not hotels.has_results()


# Priority: Low
@pytest.mark.slow
def test_checkin_date_100_years_in_the_future_eg_21231231(page):
    """TC-6: Check-in date 100 years in the future (e.g., `2123-12-31`)"""
    hotels = HotelsPage(page)
    hotels.open()

    hotels.checkin_input.fill("2123-12-31")
    hotels.search_button.click()
    page.wait_for_load_state("networkidle")
    error = page.locator(".error, .alert, [class*='error']").first
    assert error.is_visible() and error.text_content() == "Check-in date exceeds maximum allowed range (100 years from today)"
    assert not hotels.has_results()


# Priority: Low
@pytest.mark.slow
def test_timezone_conflict_eg_checkin_in_utc_vs_local_time(page):
    """TC-7: Timezone conflict (e.g., check-in in UTC vs. local time)"""
    hotels = HotelsPage(page)
    hotels.open()

    hotels.checkin_input.fill("2023-12-31")
    hotels.search_button.click()
    page.wait_for_load_state("networkidle")
    error = page.locator(".error, .alert, [class*='error']").first
    assert error.text_content() == "Check-in date conflicts with timezone. Please use UTC format (e.g., 2023-12-31T23:59:00Z)"
    assert not hotels.has_results()

